local_costmap:
   global_frame: /odom
   robot_base_frame: /base_footprint
   update_frequency: 5.0
   publish_frequency: 5.0
   static_map: false
   rolling_window: true
   width: 14.0
   height: 14.0
   resolution: 0.1
   transform_tolerance: 0.5
